import { useState, useEffect, useMemo, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, BrainCircuit, ChevronLeft, CheckCircle2, XCircle, Zap, Timer, Trophy, RotateCcw, ArrowRight } from 'lucide-react';
import { generateQuiz } from '../services/apiClient';
import { useNavigation } from '../context/NavigationContext';

/* ═══════════════════════════════════════════════════════════════
   HOLOGRAM TESTING CENTER — NEURAL EXAM ARENA
   A futuristic, high-stakes holographic quiz experience
   ═══════════════════════════════════════════════════════════════ */

export default function AITestingCenterScreen({ directText, onExitPortal }) {
    const { navigate: onNavigate } = useNavigation();
    const [latestAiText, setLatestAiText] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [quizData, setQuizData] = useState(null);
    const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
    const [selectedAnswer, setSelectedAnswer] = useState(null);
    const [isCorrect, setIsCorrect] = useState(null);
    const [score, setScore] = useState(0);
    const [showResults, setShowResults] = useState(false);
    const [timeRemaining, setTimeRemaining] = useState(30);
    const [isTimerActive, setIsTimerActive] = useState(false);
    const [streak, setStreak] = useState(0);
    const [showFlash, setShowFlash] = useState(null); // 'correct' | 'wrong' | null
    const [errorMessage, setErrorMessage] = useState(null);
    const [wrongAnswers, setWrongAnswers] = useState([]);
    const timerRef = useRef(null);
    const hasAutoGenerated = useRef(false);

    useEffect(() => {
        if (directText) {
            setLatestAiText(directText);
        } else {
            const savedText = localStorage.getItem('latestAiText');
            if (savedText) setLatestAiText(savedText);
        }
    }, [directText]);

    // ─── AUTO-GENERATE quiz when text becomes available ───
    useEffect(() => {
        if (latestAiText && !quizData && !isGenerating && !hasAutoGenerated.current) {
            hasAutoGenerated.current = true;
            handleInitializeExam();
        }
    }, [latestAiText]);

    // Particle positions (memoized for stable renders)
    const particles = useMemo(() => {
        return [...Array(30)].map(() => ({
            left: `${Math.random() * 100}%`,
            top: `${Math.random() * 100}%`,
            size: `${Math.random() * 3 + 1}px`,
            opacity: Math.random() * 0.4 + 0.1,
            duration: `${Math.random() * 12 + 8}s`,
            delay: `${Math.random() * 6}s`,
            color: Math.random() > 0.5 ? '#00F0FF' : '#A855F7',
        }));
    }, []);

    // Grid lines for 3D perspective floor
    const gridLines = useMemo(() => {
        return [...Array(12)].map((_, i) => ({
            offset: `${(i / 12) * 100}%`,
            opacity: 0.06 + (i / 12) * 0.08,
        }));
    }, []);

    // Timer countdown
    useEffect(() => {
        if (isTimerActive && timeRemaining > 0) {
            timerRef.current = setTimeout(() => {
                setTimeRemaining(prev => prev - 1);
            }, 1000);
        } else if (timeRemaining === 0 && isTimerActive) {
            // Time's up — auto-advance
            handleTimeUp();
        }
        return () => clearTimeout(timerRef.current);
    }, [isTimerActive, timeRemaining]);

    const handleTimeUp = useCallback(() => {
        if (selectedAnswer !== null) return;
        setSelectedAnswer('__timeout__');
        setIsCorrect(false);
        setStreak(0);
        setShowFlash('wrong');
        // Track timed-out question as wrong
        if (quizData && quizData[currentQuestionIndex]) {
            const q = quizData[currentQuestionIndex];
            setWrongAnswers(prev => [...prev, { question: q.question, userAnswer: '⏱️ Time Expired', correctAnswer: q.correctAnswer }]);
        }
        setTimeout(() => {
            setShowFlash(null);
            advanceQuestion();
        }, 1500);
    }, [selectedAnswer, currentQuestionIndex, quizData]);

    const advanceQuestion = useCallback(() => {
        if (quizData && currentQuestionIndex + 1 < quizData.length) {
            setCurrentQuestionIndex(prev => prev + 1);
            setSelectedAnswer(null);
            setIsCorrect(null);
            setTimeRemaining(30);
            setIsTimerActive(true);
        } else {
            setIsTimerActive(false);
            setShowResults(true);
        }
    }, [currentQuestionIndex, quizData]);

    const handleInitializeExam = async () => {
        if (!latestAiText) return;

        setIsGenerating(true);
        setQuizData(null);
        setCurrentQuestionIndex(0);
        setSelectedAnswer(null);
        setIsCorrect(null);
        setScore(0);
        setStreak(0);
        setShowResults(false);
        setTimeRemaining(30);
        setErrorMessage(null);
        setWrongAnswers([]);

        try {
            // Send to backend proxy — POST /api/ai/generate-quiz
            const result = await generateQuiz(latestAiText.substring(0, 200), 3);
            const replyText = result?.reply || '';

            // Parse the JSON quiz data from the AI reply
            let quizJson;
            try {
                const cleaned = replyText.replace(/```json/gi, '').replace(/```/g, '').trim();
                const parsed = JSON.parse(cleaned);
                // Backend returns { questions: [...] } format
                quizJson = parsed.questions || parsed;
            } catch {
                quizJson = null;
            }

            if (quizJson && Array.isArray(quizJson) && quizJson.length > 0) {
                // Normalize field names — backend uses correct/correctAnswer
                const normalized = quizJson.map(q => ({
                    question: q.question,
                    options: q.options,
                    correctAnswer: q.correctAnswer || q.correct || q.options?.[0],
                }));
                setQuizData(normalized);
                setIsTimerActive(true);
            } else {
                setErrorMessage('AI returned an unexpected format. Please retry.');
            }
        } catch (err) {
            const msg = err?.status === 401
                ? 'Session expired. Please log in again.'
                : err?.message || 'Failed to generate quiz.';
            setErrorMessage(msg);
        }
        setIsGenerating(false);
    };

    const handleAnswerClick = (option, correctAnswer) => {
        if (selectedAnswer !== null) return;
        clearTimeout(timerRef.current);
        setIsTimerActive(false);

        setSelectedAnswer(option);
        const correct = option === correctAnswer;
        setIsCorrect(correct);

        if (correct) {
            setScore(prev => prev + 1);
            setStreak(prev => prev + 1);
            setShowFlash('correct');
        } else {
            setStreak(0);
            setShowFlash('wrong');
            // Track this wrong answer for skill gap analysis
            if (quizData && quizData[currentQuestionIndex]) {
                const q = quizData[currentQuestionIndex];
                setWrongAnswers(prev => [...prev, { question: q.question, userAnswer: option, correctAnswer: q.correctAnswer }]);
            }
        }

        setTimeout(() => {
            setShowFlash(null);
            advanceQuestion();
        }, 1800);
    };

    const handleGoBack = () => {
        if (onExitPortal) {
            onExitPortal();
        } else {
            onNavigate('academic-hub');
        }
    };

    const timerColor = timeRemaining > 15 ? '#00F0FF' : timeRemaining > 7 ? '#FFD700' : '#EF4444';
    const timerPct = (timeRemaining / 30) * 100;

    return (
        <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            className="fixed inset-0 z-50 flex flex-col items-center justify-center overflow-hidden"
            style={{ fontFamily: "'Montserrat', sans-serif" }}
        >
            {/* ─── FULL-SCREEN FLASH EFFECT ─── */}
            <AnimatePresence>
                {showFlash && (
                    <motion.div
                        initial={{ opacity: 0.6 }}
                        animate={{ opacity: 0 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 0.8 }}
                        className="fixed inset-0 z-50 pointer-events-none"
                        style={{
                            background: showFlash === 'correct'
                                ? 'radial-gradient(circle at center, rgba(16,185,129,0.3) 0%, transparent 70%)'
                                : 'radial-gradient(circle at center, rgba(239,68,68,0.3) 0%, transparent 70%)'
                        }}
                    />
                )}
            </AnimatePresence>

            {/* ─── HOLOGRAPHIC 3D GRID FLOOR ─── */}
            <div className="absolute inset-0 pointer-events-none z-0" style={{
                background: 'radial-gradient(ellipse at bottom, rgba(0,240,255,0.08) 0%, #020208 70%)',
            }}>
                <div style={{
                    position: 'absolute',
                    bottom: 0, left: 0, right: 0, height: '65%',
                    backgroundSize: '50px 50px',
                    backgroundImage: 'linear-gradient(to right, rgba(0,240,255,0.07) 1px, transparent 1px), linear-gradient(to bottom, rgba(168,85,247,0.07) 1px, transparent 1px)',
                    transform: 'perspective(400px) rotateX(65deg) scale(2.5)',
                    transformOrigin: 'bottom center',
                    maskImage: 'linear-gradient(to top, black 30%, transparent 100%)',
                    WebkitMaskImage: 'linear-gradient(to top, black 30%, transparent 100%)',
                }} />
            </div>

            {/* Ambient Orbs */}
            <div className="absolute top-[15%] left-[15%] w-[500px] h-[500px] rounded-full pointer-events-none" style={{ background: 'radial-gradient(circle, rgba(0,240,255,0.12) 0%, transparent 60%)', filter: 'blur(80px)' }} />
            <div className="absolute bottom-[5%] right-[10%] w-[600px] h-[600px] rounded-full pointer-events-none" style={{ background: 'radial-gradient(circle, rgba(168,85,247,0.08) 0%, transparent 60%)', filter: 'blur(100px)' }} />
            <div className="absolute top-[50%] left-[50%] -translate-x-1/2 -translate-y-1/2 w-[300px] h-[300px] rounded-full pointer-events-none" style={{ background: 'radial-gradient(circle, rgba(0,240,255,0.05) 0%, transparent 60%)', filter: 'blur(60px)' }} />

            {/* Floating Particles */}
            <div className="absolute inset-0 pointer-events-none z-0 overflow-hidden">
                {particles.map((p, i) => (
                    <div
                        key={i}
                        className="absolute rounded-full"
                        style={{
                            left: p.left,
                            top: p.top,
                            width: p.size,
                            height: p.size,
                            opacity: p.opacity,
                            background: p.color,
                            boxShadow: `0 0 8px ${p.color}`,
                            animation: `floatUp ${p.duration} linear infinite`,
                            animationDelay: p.delay,
                        }}
                    />
                ))}
            </div>

            {/* ─── HUD OVERLAY ─── */}
            <div className="absolute top-0 left-0 w-full z-50">
                {/* Top Navigation Bar */}
                <div className="flex items-center justify-between px-6 py-4">
                    <div className="flex items-center gap-4">
                        <button
                            onClick={handleGoBack}
                            className="flex items-center justify-center w-10 h-10 rounded-full border border-white/10 text-white/70 hover:bg-white/10 hover:border-[#00F0FF]/60 hover:text-white transition-all cursor-pointer group"
                            style={{ background: 'rgba(255,255,255,0.03)', backdropFilter: 'blur(20px)' }}
                        >
                            <ChevronLeft size={18} className="group-hover:-translate-x-1 transition-transform" />
                        </button>
                        <div>
                            <h2 className="text-[16px] font-bold tracking-[0.15em] uppercase text-transparent bg-clip-text" style={{ backgroundImage: 'linear-gradient(to right, #00F0FF, #A855F7)' }}>
                                {onExitPortal ? 'Neural Portal' : 'Hologram Testing Center'}
                            </h2>
                            <p className="text-[9px] text-white/40 tracking-[0.25em] uppercase">
                                {onExitPortal ? 'Exit Portal to Return' : 'Neural Verification Engine'}
                            </p>
                        </div>
                    </div>

                    {/* HUD Stats — Only show during active quiz */}
                    {quizData && !showResults && (
                        <div className="flex items-center gap-6">
                            {/* Neural Score */}
                            <div className="flex items-center gap-2" style={{ background: 'rgba(0,240,255,0.05)', border: '1px solid rgba(0,240,255,0.2)', borderRadius: '12px', padding: '6px 14px', backdropFilter: 'blur(10px)' }}>
                                <Zap size={14} color="#00F0FF" style={{ filter: 'drop-shadow(0 0 4px #00F0FF)' }} />
                                <span className="text-[12px] font-black tracking-widest text-[#00F0FF]" style={{ textShadow: '0 0 8px rgba(0,240,255,0.5)' }}>
                                    {score}
                                </span>
                                <span className="text-[9px] font-bold tracking-wider text-white/30 uppercase">Score</span>
                            </div>

                            {/* Streak Counter */}
                            {streak > 1 && (
                                <div className="flex items-center gap-1.5" style={{ background: 'rgba(255,215,0,0.08)', border: '1px solid rgba(255,215,0,0.3)', borderRadius: '12px', padding: '6px 12px', backdropFilter: 'blur(10px)' }}>
                                    <span className="text-[12px] font-black text-[#FFD700]" style={{ textShadow: '0 0 8px rgba(255,215,0,0.5)' }}>🔥 {streak}x</span>
                                </div>
                            )}

                            {/* Timer */}
                            <div className="flex items-center gap-2 relative" style={{ background: 'rgba(0,0,0,0.3)', border: `1px solid ${timerColor}30`, borderRadius: '12px', padding: '6px 14px', backdropFilter: 'blur(10px)' }}>
                                <Timer size={14} color={timerColor} style={{ filter: `drop-shadow(0 0 4px ${timerColor})`, animation: timeRemaining <= 7 ? 'hudPulse 0.5s ease-in-out infinite' : 'none' }} />
                                <span className="text-[14px] font-black tracking-wider" style={{ color: timerColor, textShadow: `0 0 8px ${timerColor}60`, fontFamily: "'Inter', monospace" }}>
                                    {String(timeRemaining).padStart(2, '0')}
                                </span>
                                {/* Timer arc bar */}
                                <div className="absolute bottom-0 left-2 right-2 h-[2px] rounded-full overflow-hidden" style={{ background: 'rgba(255,255,255,0.05)' }}>
                                    <div style={{ width: `${timerPct}%`, height: '100%', background: timerColor, boxShadow: `0 0 6px ${timerColor}`, transition: 'width 1s linear, background 0.3s ease' }} />
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </div>

            {/* ─── MAIN ARENA TERMINAL ─── */}
            <div className="relative z-10 w-full max-w-3xl px-4 shrink-0">
                <div
                    className="w-full p-1"
                    style={{
                        background: 'linear-gradient(135deg, rgba(0,240,255,0.15) 0%, rgba(168,85,247,0.08) 100%)',
                        borderRadius: '28px',
                        boxShadow: '0 0 60px rgba(0,0,0,0.8), 0 0 30px rgba(0,240,255,0.05)',
                    }}
                >
                    <div
                        className="w-full flex flex-col items-center justify-center p-8 md:p-10"
                        style={{
                            background: 'rgba(5,5,18,0.7)',
                            backdropFilter: 'blur(60px)',
                            WebkitBackdropFilter: 'blur(60px)',
                            borderRadius: '27px',
                            border: '1px solid rgba(255,255,255,0.04)',
                            boxShadow: 'inset 0 0 60px rgba(0,240,255,0.03), inset 0 1px 0 rgba(255,255,255,0.06)',
                            minHeight: '420px',
                        }}
                    >
                        <AnimatePresence mode="wait">
                            {/* ═══ STATE 1: ERROR / RETRY ═══ */}
                            {!isGenerating && !quizData && latestAiText && errorMessage && (
                                <motion.div
                                    key="error"
                                    initial={{ opacity: 0, y: 30 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    exit={{ opacity: 0, y: -30 }}
                                    className="flex flex-col items-center gap-6 text-center"
                                >
                                    <div className="relative">
                                        <div className="absolute inset-[-20px] rounded-full" style={{ background: 'radial-gradient(circle, rgba(239,68,68,0.2) 0%, transparent 70%)', filter: 'blur(20px)' }} />
                                        <XCircle size={60} color="#EF4444" strokeWidth={1} style={{ filter: 'drop-shadow(0 0 15px rgba(239,68,68,0.5))' }} />
                                    </div>
                                    <div>
                                        <h3 className="text-xl font-black tracking-[0.15em] uppercase text-white mb-3">Neural Link Failed</h3>
                                        <p className="text-[12px] text-white/40 tracking-wider max-w-sm mb-2">Unable to generate assessment from the Gemini Neural Core.</p>
                                        <p className="text-[10px] text-red-400/60 font-mono tracking-wider max-w-sm">{errorMessage}</p>
                                    </div>
                                    <button
                                        onClick={() => { hasAutoGenerated.current = false; handleInitializeExam(); }}
                                        className="cursor-pointer flex items-center gap-2 rounded-xl font-bold tracking-[0.2em] uppercase text-[12px] text-white px-8 py-3 transition-all outline-none"
                                        style={{
                                            background: 'rgba(239,68,68,0.1)',
                                            border: '1px solid rgba(239,68,68,0.3)',
                                        }}
                                        onMouseEnter={(e) => { e.currentTarget.style.boxShadow = '0 0 25px rgba(239,68,68,0.3)'; e.currentTarget.style.borderColor = 'rgba(239,68,68,0.6)'; }}
                                        onMouseLeave={(e) => { e.currentTarget.style.boxShadow = 'none'; e.currentTarget.style.borderColor = 'rgba(239,68,68,0.3)'; }}
                                    >
                                        <RotateCcw size={14} /> Retry Connection
                                    </button>
                                </motion.div>
                            )}

                            {/* ═══ STATE 1b: AUTO-GENERATING (waiting) ═══ */}
                            {!isGenerating && !quizData && latestAiText && !errorMessage && (
                                <motion.div
                                    key="waiting"
                                    initial={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    exit={{ opacity: 0 }}
                                    className="flex flex-col items-center gap-6 text-center"
                                >
                                    <Sparkles size={50} color="rgba(0,240,255,0.2)" strokeWidth={1} />
                                    <p className="text-[11px] text-white/30 tracking-wider">Preparing neural pathways...</p>
                                </motion.div>
                            )}

                            {/* ═══ STATE 2: NO DATA ═══ */}
                            {!isGenerating && !quizData && !latestAiText && (
                                <motion.div
                                    key="empty"
                                    initial={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    exit={{ opacity: 0 }}
                                    className="flex flex-col items-center gap-6 text-center"
                                >
                                    <BrainCircuit size={60} color="rgba(255,255,255,0.15)" strokeWidth={1} />
                                    <div>
                                        <h3 className="text-xl font-bold tracking-[0.15em] uppercase text-white/30 mb-2">No Subject Data</h3>
                                        <p className="text-[12px] text-white/20 tracking-wider max-w-sm">Generate an academic projection in the AI Cinematic Lab first to sync neural data.</p>
                                    </div>
                                </motion.div>
                            )}

                            {/* ═══ STATE 3: GENERATING ═══ */}
                            {isGenerating && (
                                <motion.div
                                    key="generating"
                                    initial={{ opacity: 0, scale: 0.9 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    exit={{ opacity: 0, scale: 1.1 }}
                                    className="flex flex-col items-center gap-8 text-center"
                                >
                                    <div className="relative">
                                        <div className="absolute inset-[-30px] rounded-full" style={{ background: 'radial-gradient(circle, rgba(168,85,247,0.25) 0%, transparent 60%)', filter: 'blur(25px)', animation: 'hudPulse 2s ease-in-out infinite' }} />
                                        <div style={{ animation: 'spin 3s linear infinite' }}>
                                            <BrainCircuit size={70} color="#A855F7" strokeWidth={1} style={{ filter: 'drop-shadow(0 0 25px #A855F7) drop-shadow(0 0 50px rgba(168,85,247,0.3))' }} />
                                        </div>
                                    </div>
                                    <div>
                                        <h3 className="text-xl font-black tracking-[0.25em] uppercase text-transparent bg-clip-text mb-3" style={{ backgroundImage: 'linear-gradient(to right, #00F0FF, #A855F7)' }}>Synthesizing Neural Exam</h3>
                                        <div className="flex items-center justify-center gap-1 mt-2">
                                            {[0, 1, 2, 3, 4].map(i => (
                                                <div key={i} className="w-2 h-2 rounded-full" style={{ background: '#A855F7', animation: `synthDot 1.5s ease-in-out infinite`, animationDelay: `${i * 0.15}s`, boxShadow: '0 0 6px #A855F7' }} />
                                            ))}
                                        </div>
                                        <p className="text-[10px] font-mono text-[#A855F7]/60 tracking-widest uppercase mt-4">connecting to deep neural pathways...</p>
                                    </div>
                                </motion.div>
                            )}

                            {/* ═══ STATE 4: ACTIVE EXAM ═══ */}
                            {!isGenerating && quizData && !showResults && (
                                <motion.div
                                    key={`q-${currentQuestionIndex}`}
                                    initial={{ opacity: 0, x: 60 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    exit={{ opacity: 0, x: -60 }}
                                    transition={{ type: "spring", stiffness: 250, damping: 28 }}
                                    className="w-full flex flex-col gap-6"
                                >
                                    {/* Progress Dots */}
                                    <div className="flex flex-col items-center text-center gap-3">
                                        <div className="flex gap-3">
                                            {quizData.map((_, idx) => (
                                                <div key={idx} className="relative" style={{ width: '32px', height: '4px', borderRadius: '2px', overflow: 'hidden', background: 'rgba(255,255,255,0.06)' }}>
                                                    <div style={{
                                                        width: idx <= currentQuestionIndex ? '100%' : '0%',
                                                        height: '100%',
                                                        background: idx === currentQuestionIndex ? 'linear-gradient(90deg, #00F0FF, #A855F7)' : 'rgba(0,240,255,0.3)',
                                                        boxShadow: idx === currentQuestionIndex ? '0 0 8px #00F0FF' : 'none',
                                                        borderRadius: '2px',
                                                        transition: 'all 0.5s ease'
                                                    }} />
                                                </div>
                                            ))}
                                        </div>
                                        <span className="text-[10px] font-bold tracking-[0.3em] text-white/30 uppercase" style={{ fontFamily: "'Inter', monospace" }}>
                                            STAGE {currentQuestionIndex + 1} OF {quizData.length}
                                        </span>
                                    </div>

                                    {/* Question Card */}
                                    <div className="text-center px-4 py-4" style={{ background: 'rgba(0,240,255,0.02)', borderRadius: '16px', border: '1px solid rgba(0,240,255,0.06)' }}>
                                        <h3 className="text-lg md:text-xl font-bold text-white/90 leading-relaxed" dir="rtl" style={{ textShadow: '0 2px 15px rgba(0,0,0,0.6)' }}>
                                            {quizData[currentQuestionIndex].question}
                                        </h3>
                                    </div>

                                    {/* Answer Options */}
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                                        {quizData[currentQuestionIndex].options.map((option, idx) => {
                                            let btnState = 'idle';
                                            if (selectedAnswer !== null) {
                                                if (option === quizData[currentQuestionIndex].correctAnswer) btnState = 'correct';
                                                else if (option === selectedAnswer) btnState = 'wrong';
                                                else btnState = 'disabled';
                                            }

                                            const stateStyles = {
                                                idle: { bg: 'rgba(255,255,255,0.02)', border: 'rgba(255,255,255,0.08)', shadow: 'none', text: 'rgba(255,255,255,0.75)' },
                                                correct: { bg: 'rgba(16,185,129,0.12)', border: 'rgba(16,185,129,0.6)', shadow: '0 0 25px rgba(16,185,129,0.25), inset 0 0 15px rgba(16,185,129,0.1)', text: '#10B981' },
                                                wrong: { bg: 'rgba(239,68,68,0.12)', border: 'rgba(239,68,68,0.6)', shadow: '0 0 25px rgba(239,68,68,0.25), inset 0 0 15px rgba(239,68,68,0.1)', text: '#EF4444' },
                                                disabled: { bg: 'transparent', border: 'rgba(255,255,255,0.02)', shadow: 'none', text: 'rgba(255,255,255,0.15)' },
                                            };
                                            const s = stateStyles[btnState];

                                            const optionLabels = ['A', 'B', 'C', 'D'];

                                            return (
                                                <motion.button
                                                    key={idx}
                                                    whileTap={selectedAnswer === null ? { scale: 0.97 } : {}}
                                                    disabled={selectedAnswer !== null}
                                                    onClick={() => handleAnswerClick(option, quizData[currentQuestionIndex].correctAnswer)}
                                                    className="relative w-full text-right p-4 rounded-2xl transition-all duration-300 outline-none flex items-center gap-3 group"
                                                    style={{
                                                        background: s.bg,
                                                        border: `1px solid ${s.border}`,
                                                        boxShadow: s.shadow,
                                                        backdropFilter: 'blur(8px)',
                                                        cursor: selectedAnswer !== null ? 'default' : 'pointer',
                                                    }}
                                                    onMouseEnter={(e) => {
                                                        if (selectedAnswer === null) {
                                                            e.currentTarget.style.background = 'rgba(0,240,255,0.08)';
                                                            e.currentTarget.style.border = '1px solid rgba(0,240,255,0.35)';
                                                            e.currentTarget.style.boxShadow = '0 0 20px rgba(0,240,255,0.15)';
                                                        }
                                                    }}
                                                    onMouseLeave={(e) => {
                                                        if (selectedAnswer === null) {
                                                            e.currentTarget.style.background = s.bg;
                                                            e.currentTarget.style.border = `1px solid ${s.border}`;
                                                            e.currentTarget.style.boxShadow = s.shadow;
                                                        }
                                                    }}
                                                >
                                                    {/* Option Label */}
                                                    <div className="w-8 h-8 shrink-0 rounded-lg flex items-center justify-center text-[11px] font-black"
                                                        style={{
                                                            background: btnState === 'correct' ? 'rgba(16,185,129,0.2)' : btnState === 'wrong' ? 'rgba(239,68,68,0.2)' : 'rgba(255,255,255,0.04)',
                                                            border: `1px solid ${btnState === 'correct' ? 'rgba(16,185,129,0.4)' : btnState === 'wrong' ? 'rgba(239,68,68,0.4)' : 'rgba(255,255,255,0.08)'}`,
                                                            color: s.text,
                                                        }}
                                                    >
                                                        {btnState === 'correct' ? <CheckCircle2 size={16} /> : btnState === 'wrong' ? <XCircle size={16} /> : optionLabels[idx]}
                                                    </div>

                                                    {/* Option Text */}
                                                    <span className="text-[14px] font-semibold flex-1" dir="rtl" style={{ color: s.text, lineHeight: 1.5 }}>
                                                        {option}
                                                    </span>
                                                </motion.button>
                                            );
                                        })}
                                    </div>
                                </motion.div>
                            )}

                            {/* ═══ STATE 5: RESULTS ═══ */}
                            {showResults && quizData && (
                                <motion.div
                                    key="results"
                                    initial={{ opacity: 0, scale: 0.85 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                                    className="flex flex-col items-center gap-5 text-center w-full"
                                >
                                    {/* ─── HEADER: Trophy + Score ─── */}
                                    <div className="relative">
                                        <div className="absolute inset-[-40px] rounded-full" style={{ background: `radial-gradient(circle, ${score === quizData.length ? 'rgba(255,215,0,0.25)' : score >= quizData.length / 2 ? 'rgba(0,240,255,0.15)' : 'rgba(239,68,68,0.15)'} 0%, transparent 60%)`, filter: 'blur(30px)' }} />
                                        <Trophy size={50} color={score === quizData.length ? '#FFD700' : score >= quizData.length / 2 ? '#00F0FF' : '#EF4444'} strokeWidth={1} style={{ filter: `drop-shadow(0 0 20px ${score === quizData.length ? '#FFD700' : '#00F0FF'})`, animation: 'hudFloat 3s ease-in-out infinite' }} />
                                    </div>

                                    <div className="text-[60px] font-black tracking-tight leading-none" style={{
                                        background: score === quizData.length ? 'linear-gradient(135deg, #FFD700, #FF8C00)' : score >= quizData.length / 2 ? 'linear-gradient(135deg, #00F0FF, #A855F7)' : 'linear-gradient(135deg, #EF4444, #F97316)',
                                        WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent',
                                        filter: `drop-shadow(0 0 15px ${score === quizData.length ? 'rgba(255,215,0,0.3)' : 'rgba(0,240,255,0.3)'})`,
                                    }}>
                                        {score}/{quizData.length}
                                    </div>

                                    <h3 className="text-lg font-bold tracking-[0.15em] uppercase text-white">
                                        {score === quizData.length ? 'Perfect Neural Sync' : score >= quizData.length / 2 ? 'Assessment Complete' : 'Calibration Required'}
                                    </h3>

                                    {/* ─── SKILL GAP ANALYSIS ─── */}
                                    <div className="w-full mt-2" style={{ background: 'rgba(0,0,0,0.3)', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.04)', padding: '16px' }}>
                                        <h4 className="text-[10px] font-bold tracking-[0.25em] uppercase text-white/40 mb-3 flex items-center gap-2 justify-center">
                                            <Zap size={12} /> Skill Gap Analysis
                                        </h4>

                                        {wrongAnswers.length === 0 ? (
                                            <div className="py-4">
                                                <div className="text-[14px] font-bold text-[#FFD700] tracking-wider" style={{ textShadow: '0 0 15px rgba(255,215,0,0.4)', animation: 'hudPulse 3s ease-in-out infinite' }}>
                                                    ✨ FLAWLESS NEURAL SYNC ✨
                                                </div>
                                                <p className="text-[11px] text-white/30 mt-2 tracking-wider">No skill gaps detected. All neural pathways fully calibrated.</p>
                                            </div>
                                        ) : (
                                            <div className="flex flex-col gap-3 max-h-[200px] overflow-y-auto pr-1" style={{ scrollbarWidth: 'thin', scrollbarColor: 'rgba(255,255,255,0.1) transparent' }}>
                                                {wrongAnswers.map((item, idx) => (
                                                    <div key={idx} className="text-left p-3 rounded-xl" style={{ background: 'rgba(239,68,68,0.05)', border: '1px solid rgba(239,68,68,0.1)' }}>
                                                        <div className="flex items-start gap-2 mb-2">
                                                            <span className="text-[10px] mt-0.5">⚠️</span>
                                                            <div>
                                                                <span className="text-[9px] font-bold tracking-widest uppercase text-red-400/70">Concept Missed</span>
                                                                <p className="text-[12px] text-white/60 leading-relaxed" dir="rtl">{item.question}</p>
                                                            </div>
                                                        </div>
                                                        <div className="flex items-start gap-2 mt-1 ml-4">
                                                            <span className="text-[10px] mt-0.5">❌</span>
                                                            <div>
                                                                <span className="text-[9px] font-bold tracking-widest uppercase text-red-400/50">Your Answer</span>
                                                                <p className="text-[11px] text-red-300/60" dir="rtl">{item.userAnswer}</p>
                                                            </div>
                                                        </div>
                                                        <div className="flex items-start gap-2 mt-1 ml-4">
                                                            <span className="text-[10px] mt-0.5">✅</span>
                                                            <div>
                                                                <span className="text-[9px] font-bold tracking-widest uppercase text-emerald-400/70">Correct Protocol</span>
                                                                <p className="text-[11px] text-emerald-300/80 font-semibold" dir="rtl">{item.correctAnswer}</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                ))}
                                            </div>
                                        )}
                                    </div>

                                    {/* ─── ACTION BUTTONS ─── */}
                                    <div className="flex gap-4 mt-2">
                                        <button
                                            onClick={handleInitializeExam}
                                            className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold tracking-widest uppercase text-[11px] border transition-all cursor-pointer outline-none"
                                            style={{ background: 'rgba(0,240,255,0.08)', color: '#00F0FF', borderColor: 'rgba(0,240,255,0.25)' }}
                                            onMouseEnter={(e) => { e.currentTarget.style.boxShadow = '0 0 20px rgba(0,240,255,0.3)'; e.currentTarget.style.borderColor = 'rgba(0,240,255,0.6)'; }}
                                            onMouseLeave={(e) => { e.currentTarget.style.boxShadow = 'none'; e.currentTarget.style.borderColor = 'rgba(0,240,255,0.25)'; }}
                                        >
                                            <RotateCcw size={14} /> Re-Calibrate
                                        </button>
                                        <button
                                            onClick={handleGoBack}
                                            className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold tracking-widest uppercase text-[11px] border transition-all cursor-pointer outline-none"
                                            style={{ background: 'rgba(255,255,255,0.04)', color: 'white', borderColor: 'rgba(255,255,255,0.08)' }}
                                            onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.08)'; }}
                                            onMouseLeave={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.04)'; }}
                                        >
                                            <ArrowRight size={14} /> {onExitPortal ? 'Exit Portal' : 'Return to Hub'}
                                        </button>
                                    </div>
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </div>
                </div>
            </div>

            {/* ─── KEYFRAMES ─── */}
            <style>{`
                @keyframes floatUp {
                    0% { transform: translateY(0) scale(1); opacity: 0; }
                    10% { opacity: 0.5; }
                    90% { opacity: 0.5; }
                    100% { transform: translateY(-600px) scale(0); opacity: 0; }
                }
                @keyframes hudFloat {
                    0%, 100% { transform: translateY(0px); }
                    50% { transform: translateY(-10px); }
                }
                @keyframes hudPulse {
                    0%, 100% { opacity: 1; transform: scale(1); }
                    50% { opacity: 0.6; transform: scale(1.1); }
                }
                @keyframes spin {
                    from { transform: rotate(0deg); }
                    to { transform: rotate(360deg); }
                }
                @keyframes synthDot {
                    0%, 100% { opacity: 0.3; transform: scale(0.8); }
                    50% { opacity: 1; transform: scale(1.3); }
                }
            `}</style>
        </motion.div>
    );
}
